### PR TITLE
Speaker id UI

### PR DESCRIPTION
**Pull request by EzraEllette**
---
name: pull request
about: submit changes to the project
title: "[pr] "
labels: ''
assignees: ''

---

## description
brief description of the changes in this pr.

related issue: #

## type of change
- [ ] bug fix
- [ ] new feature
- [ ] breaking change
- [ ] documentation update

## how to test

add a few steps to test the pr in the most time efficient way.

1. 
2. 
3. 

if relevant add screenshots or screen captures to prove that this PR works to save us time.

## checklist
- [ ] MOST IMPORTANT: this PR will require less than 30 min to review, merge, and release to production and not crash in the hand of thousands of users
- [ ] i have read the [CONTRIBUTING.md](https://github.com/mediar-ai/screenpipe/blob/main/CONTRIBUTING.md) file 
- [ ] i have updated the documentation if necessary
- [ ] my changes generate no new warnings
- [ ] i have added tests that prove my fix is effective or that my feature works

## additional notes
any other relevant information about the pr.

### CODE REVIEW

**Comment by EzraEllette** [comment]
Changes to make:

1. add section to compare voices and set either same or name other voice.
2. Move identification menu button to hanburger menu.
3. When pressing identify for a menu, bring up the menu for that specific meeting's speakers.
4. Improve speaker identification similarity threshold.

**Comment by louis030195** [comment]
> Changes to make:
> 
> 1. add section to compare voices and set either same or name other voice.
> 2. Move identification menu button to hanburger menu.
> 3. When pressing identify for a menu, bring up the menu for that specific meeting's speakers.
> 4. Improve speaker identification similarity threshold.

any news on this?

**Comment by EzraEllette** [comment]
I'm working on this today. The holiday weekend was very busy for me.

**Comment by EzraEllette** [comment]
I have everything complete except for the voice comparison. Finishing up testing, then I'll work on the voice comparison ui.

**Comment by louis030195** [comment]
@EzraEllette nice!!

can you fix conflicts?

also what do i need to do to test efficiently?

**Comment by EzraEllette** [comment]
I'll fix conflicts. Go to a meeting and select identify speakers. Also go to the hamburger menu and test that you can add speakers and merge speakers that you have already identified. I think that if I have to explain too much that would just mean i need to fix the UX, so let me know if it's confusing.

**Comment by louis030195** [comment]
Screenshot 2024-12-03 at 2 00 23 PM

few things:
- we try to use only black and white colors in general (no red) with a few exception like status (an icon might be better)
- lower case
- why is the bottom audio things not showing same audio player with length etc?
- use icons in button
- i noticed i did not read the text at the top (tried things before)
- does it make sense to make a list of people (with no names or names defined by user) like google photo and upon click it would open the list of samples from them?
- not sure "hallucination" is the right word, maybe could be just "delete"?
- why my sample audio are only 1s?


Screenshot 2024-12-03 at 2 02 38 PM

Screenshot 2024-12-03 at 2 06 56 PM


Screenshot 2024-12-03 at 2 07 25 PM

**Comment by EzraEllette** [comment]
- [ ] use only black and white colors
- [ ] lower case
- [ ] fix audio player
- [ ] use icons in button
- [ ] the text is useless, remove it
- [ ] add speaker explorer
- [ ] remove usage of hallucination, use something like "nobody is talking".

- why my sample audio are only 1s?
  - I noticed this and initially intended to try to select longer audio chunks, but the segmentation process can track short segments, so maybe we should ignore segments under a specified duration.

**Comment by louis030195** [comment]
amazing work - love this

**Pull request merged**
