### PR TITLE
feat: add icons in timeline for windows

### PR DESCRIPTION
**Pull request by tribhuwan-kumar**
---
name: add icons in timeline for windows
about: it can currently exe of installed apps using `Get-AppxPackage` for microsoft installed apps, from registry key for installed application from installer, and searches in potential path like start menu and and `C:\windows` to get the exe path by app name, then it extracts icons from .exe and .lnk (modified [zmconnelly/windows-icons](https://github.com/zmconnelly/windows-icons) this crate to [tribhuwan-kumar/windows-icons](https://github.com/tribhuwan-kumar/windows-icons)
title: #643
labels: ''
assignees: ''

ps: it took some time to load all icons, maybe some asynchronous issue, fixing it
Screenshot 2024-11-20 121950

fix: #643

---

## description

related issue: #

## type of change
- [ ] bug fix
- [ ] new feature
- [ ] breaking change
- [ ] documentation update

## how to test

add a few steps to test the pr in the most time efficient way.

1. 
2. 
3. 

if relevant add screenshots or screen captures to prove that this PR works to save us time.

## checklist
- [ ] MOST IMPORTANT: this PR will require less than 30 min to review, merge, and release to production and not crash in the hand of thousands of users
- [ ] i have read the [CONTRIBUTING.md](https://github.com/mediar-ai/screenpipe/blob/main/CONTRIBUTING.md) file 
- [ ] i have updated the documentation if necessary
- [ ] my changes generate no new warnings
- [ ] i have added tests that prove my fix is effective or that my feature works

## additional notes
any other relevant information about the pr.

### CODE REVIEW

**Comment by louis030195** [comment]
@tribhuwan-kumar nice!

just wondering - what happen if this fail for some reason, does it crash the timeline? should not

for example if cannot find powershell or something like this

otherwise looks good to me!

**Comment by tribhuwan-kumar** [comment]
> @tribhuwan-kumar nice!
> 
> just wondering - what happen if this fail for some reason, does it crash the timeline? should not
> 
> for example if cannot find powershell or something like this
> 
> otherwise looks good to me!
> 

nope, it'll not crash the timeline
if it's can't find icon of any application it'll simply log error in console!

**Comment by louis030195** [comment]
> Could not find a claim that corresponds to the PR. Please add the `/claim` snippet to the PR body first.

@tribhuwan-kumar make sure to add claim

thanks for amazing work!

can you also do the linux one?

**Comment by tribhuwan-kumar** [comment]
you opened new issue for linux, probably i should claim it
/claim #643

**Comment by tribhuwan-kumar** [comment]
> > Could not find a claim that corresponds to the PR. Please add the `/claim` snippet to the PR body first.
> 
> @tribhuwan-kumar make sure to add claim
> 
> thanks for amazing work!
> 
> can you also do the linux one?

i added the claim, maybe you've to approve again!

**Comment by tribhuwan-kumar** [comment]
> > Could not find a claim that corresponds to the PR. Please add the `/claim` snippet to the PR body first.
> 
> @tribhuwan-kumar make sure to add claim
> 
> thanks for amazing work!
> 
> can you also do the linux one?

@louis030195 
i added the claim, maybe you've to approve again!

**Pull request merged**
