### PR TITLE
Retry with GitHub runner if self-hosted fails

### LINKED ISSUE #831: [bounty] make release-app windows run on self hosted by default and fallback to github if self hosted fails
/bounty 100

### PR DESCRIPTION
**Pull request by Neptune650**
/claim #831
/closes  #831

@louis030195 Retries with the GitHub runner in case the self-hosted runner fails

Another option is using composite actions, i.e steps would be on another file.

### CODE REVIEW

**Comment by louis030195** [comment]
can you do composite? will be too hard to maintain otherwise

**Comment by Neptune650** [comment]
> can you do composite? will be too hard to maintain otherwise

@louis030195 okay

**Comment by Neptune650** [comment]
@louis030195 Done, please merge.

**Comment by Neptune650** [comment]
@louis030195 Conflicts fixed.

**Pull request merged**
