### PR TITLE
fix: brew update

### PR DESCRIPTION
**Pull request by krushnarout**
---
name: pull request
about: submit changes to the project
title: fix: brew update
labels: ''
assignees: ''

---

## description
brief description of the changes in this pr.

related issue: #

## type of change
- [ ] bug fix
- [ ] new feature
- [ ] breaking change
- [ ] documentation update

## how to test

add a few steps to test the pr in the most time efficient way.

1. 
2. 
3. 

if relevant add screenshots or screen captures to prove that this PR works to save us time.

## checklist
- [ ] MOST IMPORTANT: this PR will require less than 30 min to review, merge, and release to production and not crash in the hand of thousands of users
- [ ] i have read the [CONTRIBUTING.md](https://github.com/mediar-ai/screenpipe/blob/main/CONTRIBUTING.md) file 
- [ ] i have updated the documentation if necessary
- [ ] my changes generate no new warnings
- [ ] i have added tests that prove my fix is effective or that my feature works

## additional notes
any other relevant information about the pr.

### CODE REVIEW

**Comment by louis030195** [comment]
@krushnarout how do you know it works?

**Comment by krushnarout** [comment]
> @krushnarout how do you know it works?

I used `--dry-run` it’s the only way I can check from my side. It prints the `sha256` correctly.

**Comment by krushnarout** [comment]
@louis030195 Please use a different version because it takes this as a duplicate PR. Otherwise, use `--force`. Ref: [Search for closed duplicate PRs as part of bump-formula-pr](https://github.com/Homebrew/brew/issues/7744). In this, a warning of a possibly duplicate PR will be printed, but it would allow a person to override it with the `--force` flag."

**Comment by krushnarout** [comment]
@louis030195 I have an idea. Instead of making the PR right away, we can simply do

Comment out the brew bump-formula-pr code and first check if it logs the URL and SHA256 correctly. If everything looks correct, then uncomment the brew bump-formula-pr code to proceed with the PR.

```
 # Log calculated values
          echo "Tarball URL: ${URL}"
          echo "Calculated SHA256: ${SHA}"

 # Update the formula using Homebrew
        # brew bump-formula-pr screenpipe \
        #   --url="${URL}" \
        #   --sha256="${SHA}" \
        #   --message="Automated update to version ${VERSION}" \
        #   --no-browse \
        #   --no-audit
```

**Pull request closed without merging**
