### PR TITLE
Health check race condition fix

### PR DESCRIPTION
**Pull request by screwyforcepush**
/claim #773

# Health Check System Improvements

## Summary of Changes
1. Enhanced `useHealthCheck` hook with debounced functionality and proper cleanup
2. Added loading states for dialog operations
3. Improved error handling and type safety
4. Implemented proper event handling for settings updates
5. Added request cancellation for stale health checks

## Key Files Modified
- `lib/hooks/use-health-check.tsx`
- `components/screenpipe-status.tsx`
- `components/settings.tsx`

## Purpose
Address intermittent button functionality issues and improve reliability of health check system by:
- Preventing race conditions in health status polling
- Adding proper request cancellation
- Implementing debounced health checks for performance
- Separating concerns between health checks and UI operations
- Improving error handling and user feedback

### Health Check Hook Improvements
```typescript
export function useHealthCheck(): HealthCheckHook {
  // Added proper type definitions
  // Implemented abort controller for request cancellation
  // Added debounced fetch functionality
  // Improved error handling with type guards
}
```

### Loading State Management
- Separated health check loading from UI operation loading
- Added visual feedback during loading states
- Implemented proper cleanup to prevent memory leaks

### Settings Integration
- Added event-based communication for settings updates
- Implemented debounced health checks to prevent unnecessary API calls
- Improved type safety with proper interfaces

## Technical Rationale
1. **Request Cancellation**: Used `AbortController` to prevent stale requests from affecting UI state
2. **Debouncing**: Implemented to reduce server load during rapid state changes
3. **Type Safety**: Added proper interfaces and type guards to catch potential issues at compile time
4. **State Management**: Separated concerns between health checks and UI operations for better maintainability
5. **Event System**: Used custom events for better decoupling between components

### CODE REVIEW

**Comment by louis030195** [comment]
how to reproduce error and test? @screwyforcepush

**Comment by louis030195** [comment]
does not fix the issue, still cant click things

**Comment by louis030195** [comment]
not sure what this PR is doing/solving

**Comment by screwyforcepush** [comment]
@louis030195 When I was trying to debug the UI elements not working. I noticed some console errors in the logs that came from server request failing. Turns out there was a race condition in the code. It may not help the UI elements not work but I thought to fix it anyway for stability.

**Comment by louis030195** [comment]
@screwyforcepush can you solve coflict and will merge

**Comment by louis030195** [comment]
> @screwyforcepush can you solve coflict and will merge

bump

**Pull request closed without merging**
