### PR TITLE
fix: video rendering issue in windows

### PR DESCRIPTION
**Pull request by tribhuwan-kumar**
fix: #319 
[demo](https://drive.google.com/file/d/1NbxUQK65aVmqEEifvIwkLY0UwY7lfgn4/view?usp=sharing)

/claim #319

### CODE REVIEW

**Comment by tribhuwan-kumar** [comment]
@defihook thanks, @louis030195 you can merge it now :)

**Comment by louis030195** [comment]
@tribhuwan-kumar last time i tried on my windows it was not working - can you send me a build at louis@screepi.pe i'll try again

**Comment by tribhuwan-kumar** [comment]
> @tribhuwan-kumar last time i tried on my windows it was not working - can you send me a build at [louis@screenpi.pe](mailto:louis@screenpi.pe) i'll try again

you mean an executable ?? [here](https://drive.google.com/drive/folders/1OI1HTWfArbhvmNZozQ5sGCt-kIA3Ch4x) it is. also [here](https://github.com/mediar-ai/screenpipe/issues/319#issuecomment-2381122254) is the detailed description what i done

**Comment by louis030195** [comment]
@tribhuwan-kumar thank you !

please let me know if you have any issues with the bounty

also if anyhow you can help with audio issues some users are facing on windows

https://github.com/mediar-ai/screenpipe/issues/374 (will add bounty)

**Comment by tribhuwan-kumar** [comment]
> @tribhuwan-kumar thank you !
> 
> please let me know if you have any issues with the bounty
> 
> also if anyhow you can help with audio issues some users are facing on windows
> 
> #374 (will add bounty)

sure, I'll try to find out what's causing that issue!

**Pull request merged**
