### PR TITLE
Settings redesign

### LINKED ISSUE #939: [bounty] $200 make settings more scalable / better / look more native
/bounty 200

plz suggest design first, take inspiration on great desktop UX like granola, idk

also i think we should put more stuff to tray menu but ok for now 

also we have tons of issues with the command component (atm cannot select audio device, like it disapear for some reason)

### LINKED ISSUE #955: [bounty] fix settings not saving properly
how to reproduce:
- change deepgram to something else 
- press save 
- right click reload 
- come back to settings, reverted

/bounty 100

### PR DESCRIPTION
**Pull request by neo773**
This is a work in progress draft PR.

Redesigned Settings to look more native inspired by macOS Settings App and Granola AI

Changes
- Split into categories
- Sidebar for easy navigation
- Added a custom `multi-select` component for cleaner UI/UX
- Revamped Toggles and Input
- Recording Settings split and grouped into further categories (audio, video, misc) via `<Separator/>` 
- AI settings include Beautiful Cards with custom icons made in Figma
- Shortcuts Redesigned, it captures keystrokes instead of user selecting it.

Demo:
There are still some bugs but this a WIP

https://github.com/user-attachments/assets/edec0046-b58d-46d2-904b-7457fbbe2bd1

/claim #939
/closes #939

/closes #955
/claim #955

### CODE REVIEW

**Comment by neo773** [comment]
Not yet, will fix it tonight

**Comment by louis030195** [comment]
also would it be possible to allow the AI model component to be a kind of dropdown so we can pick some models from the list or write the name ourselve

assuming most AI provider are exposing an API list or we can just hardcode some models 

screenpipe cloud support anthropic and openai atm

**Comment by louis030195** [comment]
image

kinda awkward

**Comment by louis030195** [comment]
if you want you can base this on your other PR for settings so we merge both in same time or something

**Comment by neo773** [comment]
Yes, as I mentioned it’s a work in progress PR

**Comment by louis030195** [comment]
as a followup to this PR (in another PR) you could do https://github.com/mediar-ai/screenpipe/issues/515

which is just adding shortcut to start / stop and to the setting 

another thing is to add shortcut to open each pipe (prob another task/pr again)

**Comment by louis030195** [comment]
/approve 

amazing

**Comment by louis030195** [comment]
image


@neo773 any idea why settings are not saved and other issues?

**Comment by louis030195** [comment]
note that ihad to change slightly settings because it was not saving as correct JSON thus broke screenpipe-js

**Comment by louis030195** [comment]
reverting to flat json and will refactor screenpipe-js

**Pull request merged**
