### PR TITLE
Added docs website using nextra

### PR DESCRIPTION
**Pull request by bhupesh-sf**
/claim #313 

Added the doc website. Search doesn't index pages automatically if we use react component. So I figured out the different way to do so. Now search works perfectly.

### CODE REVIEW

**Comment by louis030195** [comment]
@bhupesh-sf i see pages dir, does this work with nextjs app dir?

**Comment by bhupesh-sf** [comment]
No, Nextra only works with the `/pages` directory at the moment. Support for the app router has not been implemented yet. But you can use `/app` and `/pages` at the same time - just put your docs inside `/pages` and your other routes in `/app`

**Comment by louis030195** [comment]
@bhupesh-sf will take a look within this hour, thanks!

**Comment by louis030195** [comment]
image
seems you overused chatgpt it hallucinated bunch of stuff

most things here are hallucinated http://localhost:3000/docs/bonus-features

please fix and reduce verbosity, less is more

actually half of the content is hallucination ... please ...

can you add visuals also you can use https://screenshot.rocks/ if you make screenshots yourself to make nice or just copy paste what we have, video etc

**Comment by bhupesh-sf** [comment]
Yeah, I tried to expand using chatGPT but I can reduce it. I will be signing off soon, so will get u by tomorrow

**Comment by bhupesh-sf** [comment]
I have made the required changes, let me know your thoughts about it.

**Comment by louis030195** [comment]
thx @bhupesh-sf lmk if any issue with the bounty

**Pull request merged**
