### PR TITLE
feat: add screenpipe cli to PATH

### LINKED ISSUE #421: make CLI available in PATH
when installing app it should put CLI in PATH (on all OSes)

### PR DESCRIPTION
**Pull request by divanshu-go**
---
name: pull request
about: submit changes to the project
title: "[PR] Feat: Add Screenpipe CLI to PATH "
labels: ''
assignees: ''

---

## description
This PR adds functionality to check whether the Screenpipe CLI is in the system PATH and automatically persists it if necessary. The changes ensure that screenpipe is easily accessible after installation without requiring manual path updates.

Closes #421 

## type of change
- [ ] bug fix
- [x] new feature
- [ ] breaking change
- [ ] documentation update

## how to test
1. download screenpipe binary or build from source
2. do `screenpipe` or `screenpipe setup`
3. make sure to follow instructions in output
4. Open a new terminal session and verify that screenpipe is available in the system PATH by running `which screenpipe` or On Windows do `where screenpipe`

## checklist
- [x] MOST IMPORTANT: this PR will require less than 30 min to review, merge, and release to production and not crash in the hand of thousands of users
- [x] i have read the [CONTRIBUTING.md](https://github.com/mediar-ai/screenpipe/blob/main/CONTRIBUTING.md) file 
- [ ] i have updated the documentation if necessary
- [x] my changes generate no new warnings
- [ ] i have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by louis030195** [comment]
cool thanks!

/tip $40 @divanshu-go

**Comment by tribhuwan-kumar** [comment]
@divanshu-go what does this mean?
```
[2m2024-11-11T13:55:01.711915Z[0m [31mERROR[0m [2mscreenpipe[0m[2m:[0m screenpipe PATH check failed: the PATH is too long to persist using 'setx'. please shorten the PATH.
[2m2024-11-11T13:55:01.711934Z[0m [31mERROR[0m [2mscreenpipe[0m[2m:[0m please ensure screenpipe is installed correctly and is in your PATH
```

**Comment by divanshu-go** [comment]
@tribhuwan-kumar we are using `setx` on windows to set PATH and maybe your PATH is already above the limit of 1024 . therefore It is not able to update(persist) the screenpipe binary path into it.
You can shorten your PATH if you want it to set up your PATH

**Comment by tribhuwan-kumar** [comment]
> @tribhuwan-kumar we are using `setx` on windows to set PATH and maybe your PATH is already above the limit of 1024 . therefore It is not able to update(persist) the screenpipe binary path into it.
> You can shorten your PATH if you want it to set up your PATH

so there is character [limit](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/setx)
but it should be more like a warning,
it doesn't let run screenpipe without adding in path.

**Comment by divanshu-go** [comment]
@tribhuwan-kumar can you suggest a fix because this limit is set by Microsoft and I can not do anything besides you shorten your PATH

**Comment by divanshu-go** [comment]
@tribhuwan-kumar you can always run the app using absolute path of binary if you do not want to set PATH

**Comment by tribhuwan-kumar** [comment]
> @tribhuwan-kumar can you suggest a fix because this limit is set by Microsoft and I can not do anything besides you shorten your PATH

can you make it something like this, if `setx` path limit exceeds it simply skip to set screenpipe in path (only for windows) bcz in app when path exceeds (`bun tauri dev`), it doesn't let run screenpipe .
maybe @louis030195 can suggest something

**Comment by louis030195** [comment]
@tribhuwan-kumar i removed the return that was preventing to run screenpipe

if it fails to add to path it shouldn't prevent running the main features

**Pull request merged**
