### PR TITLE
Feat:add ffmpeg sidecar for ffmpeg installation

### LINKED ISSUE #194: switch to ffmpeg-sidecar
https://github.com/CapSoftware/ffmpeg-sidecar

https://github.com/CapSoftware/Cap/blob/63719073805f1fd040343ae27366272a29918078/apps/desktop/src-tauri/src/main.rs#L75

switch to use this lib to install ffmpeg in screenpipe lib

Update: little concern with cap fork is that it's using their s3 ffmpeg build so if they close it, product is down, but can work around this later i guess

### PR DESCRIPTION
**Pull request by Mubashirshariq**
/claim  #194
/closes  #194

### CODE REVIEW

**Comment by louis030195** [comment]
@Mubashirshariq hey thanks for this!

this is a good start, but this is just a function unused in a corner

here's what's missing:
- instructions to test and see screenpipe works without having manually ffmpeg installed beforehand
- running this somewhere, say in the CLI `screenpipe-server.rs`
- i can run the install instructions from README without the ffmpeg part and it works
- i can remove the ffmpeg installation in brew and it works
- i can remove the ffmpeg installation from [app pre build](https://github.com/mediar-ai/screenpipe/blob/main/examples/apps/screenpipe-app-tauri/scripts/pre_build.js) and it works 

i'd add tips for things like (but optional):
- [h265 encoding](https://github.com/nathanbabcock/ffmpeg-sidecar/blob/main/examples/h265_transcode.rs) which should reduce storage required
- well tested on all OSes and i don't have to test myself 
- good unit tests that check in CI that ffmpeg is usable on all OSes using different runners

**Comment by Mubashirshariq** [comment]
sure i will test it and share the video

**Comment by louis030195** [comment]
@Mubashirshariq are you on Linux wayland ?

ATM screenpipe vision does not work with Linux wayland (but does with X)

**Comment by Mubashirshariq** [comment]
yeah i am Linux Wayland,so i think i need to wait for this one ,i am getting a new machine next week

**Comment by Mubashirshariq** [comment]
@louis030195  i did comment the ffmpeg installation code in prebuild and pushed some changes and it is now working perfect ,attaching the recording the same

https://drive.google.com/file/d/16BROsTSFbuMbSA7LAumNpqkxMMtSqH2T/view?usp=drive_link

**Comment by Mubashirshariq** [comment]
I have gave you the access

**Comment by Mubashirshariq** [comment]
@louis030195, have you looked into this video and the overall PR?

**Comment by louis030195** [comment]
@Mubashirshariq i just think this is missing lot of things, if i merge i will have to remove all the rest of the things that install ffmpeg myself like pre_build.js script, CI/CD, etc etc

**Comment by Mubashirshariq** [comment]
@louis030195 if it is working fine and you tested  it will remove those that is not an issue

**Comment by Mubashirshariq** [comment]
@louis030195  can you look i have removed the ffmpeg installation from prebuild and workflows

**Pull request closed without merging**
