### PR TITLE
Fix/add ffmpeg sidecar

### LINKED ISSUE #194: switch to ffmpeg-sidecar
https://github.com/CapSoftware/ffmpeg-sidecar

https://github.com/CapSoftware/Cap/blob/63719073805f1fd040343ae27366272a29918078/apps/desktop/src-tauri/src/main.rs#L75

switch to use this lib to install ffmpeg in screenpipe lib

Update: little concern with cap fork is that it's using their s3 ffmpeg build so if they close it, product is down, but can work around this later i guess

### PR DESCRIPTION
**Pull request by Mubashirshariq**
/claim #194 
/closes #194

1)added ffmpeg sidecar from cap fork
2)removed manual installation of ffmpeg from ci/cd and prebuild

### CODE REVIEW

**Comment by louis030195** [comment]
@Mubashirshariq how long does it take to download?

does it work in the built app? does macos block the download? 

if the internet is slow does the app get stuck for 10 min without user feedback?

**Comment by Mubashirshariq** [comment]
@louis030195 attaching the ss of same 
Screenshot 2024-10-01 at 2 13 11 AM

when i run it again it runs

Screenshot 2024-10-01 at 2 13 11 AM

**Comment by Mubashirshariq** [comment]
> @Mubashirshariq how long does it take to download?
> 
> does it work in the built app? does macos block the download?
> 
> if the internet is slow does the app get stuck for 10 min without user feedback?

1)It takes 10-20 seconds to download when the internet speed is high and it gets stuck for around 8-9 minutes if the speed is slow.

**Comment by louis030195** [comment]
suggestion: can you make a `screenpipe setup` command in the CLI that would setup a few thing like ffmpeg (just calling the function) and log something to terminal, ideally i will use this command in the app UI later in the onboarding and stream progress in the UI (i will do this part you don't need to)

few concerns left about this PR:
- different version of ffmpeg does not cause encoding issues (audio and video), still work on both macos, windows, linux (can skip testing linux)
- in app UI video still render in the UI (different ffmpeg encoding might cause issue here) on macos, windows

then can merge

**Comment by Mubashirshariq** [comment]
@louis030195  yeah sure,did you pushed it

**Comment by louis030195** [comment]
https://github.com/mediar-ai/screenpipe/blob/58390871652302323f3f8c7fb55f7eb604503031/screenpipe-server/src/bin/screenpipe-server.rs#L124

@Mubashirshariq

**Comment by Mubashirshariq** [comment]
@louis030195  i have added ffmpeg installation to the setup command attaching the ss of same

Screenshot 2024-10-17 at 12 17 31 AM

**Comment by louis030195** [comment]
@Mubashirshariq cool!

let me some time to test out bunch of things we just released, will test this tomorrow

**Comment by louis030195** [comment]
```
(env) (base) louisbeaumont@louisbeaumontme-macbook:~/Documents/screen-pipe$ ./target/release/screenpipe --debug
2024-10-17T22:14:41.912437Z  INFO screenpipe: logging initialized
2024-10-17T22:14:41.912484Z DEBUG screenpipe_core::ffmpeg: Starting search for ffmpeg executable    
2024-10-17T22:14:41.912677Z DEBUG screenpipe_core::ffmpeg: ffmpeg not found in PATH    
2024-10-17T22:14:41.912703Z DEBUG screenpipe_core::ffmpeg: Current working directory: "/Users/louisbeaumont/Documents/screen-pipe"    
2024-10-17T22:14:41.912715Z DEBUG screenpipe_core::ffmpeg: ffmpeg not found in current working directory    
2024-10-17T22:14:41.912719Z DEBUG screenpipe_core::ffmpeg: Executable folder: "/Users/louisbeaumont/Documents/screen-pipe/target/release"    
2024-10-17T22:14:41.912736Z DEBUG screenpipe_core::ffmpeg: Found ffmpeg in executable folder: "/Users/louisbeaumont/Documents/screen-pipe/target/release/ffmpeg"    
2024-10-17T22:14:42.262006Z  INFO screenpipe:   MacBook Pro Microphone (input)
2024-10-17T22:14:42.262032Z  INFO screenpipe:   Display 1 (output)
2024-10-17T22:14:42.262044Z DEBUG screenpipe_server::db: Initializing DatabaseManager with database path: /Users/louisbeaumont/.screenpipe/db.sqlite    
2024-10-17T22:14:42.263430Z  INFO screenpipe_server::db: Migrations executed successfully.    
2024-10-17T22:14:42.263443Z  INFO screenpipe: database initialized, will store files in /Users/louisbeaumont/.screenpipe



                                            _          
   __________________  ___  ____     ____  (_____  ___ 
  / ___/ ___/ ___/ _ \/ _ \/ __ \   / __ \/ / __ \/ _ \
 (__  / /__/ /  /  __/  __/ / / /  / /_/ / / /_/ /  __/
/____/\___/_/   \___/\___/_/ /_/  / .___/_/ .___/\___/ 
                                 /_/     /_/           



build ai apps that have the full context
open source | runs locally | developer friendly


┌─────────────────────┬────────────────────────────────────┐
│ setting             │ value                              │
├─────────────────────┼────────────────────────────────────┤
│ fps                 │ 0.2                                │
│ audio chunk duration│ 30 seconds                         │
│ video chunk duration│ 60 seconds                         │
│ port                │ 3030                               │
│ audio disabled      │ false                              │
│ vision disabled     │ false                              │
│ save text files     │ false                              │
│ audio engine        │ WhisperLargeV3Turbo                │
│ ocr engine          │ AppleNative                        │
│ vad engine          │ Silero                             │
│ vad sensitivity     │ High                               │
│ data directory      │ /Users/louisbeaumont/.screenpipe   │
│ debug mode          │ true                               │
│ telemetry           │ true                               │
│ local llm           │ false                              │
│ use pii removal     │ false                              │
│ ignored windows     │ []                                 │
│ included windows    │ []                                 │
│ friend wearable uid │ not set                            │
├─────────────────────┼────────────────────────────────────┤
│ monitors            │                                    │
2024-10-17T22:14:42.263818Z DEBUG screenpipe_audio::whisper: Initializing WhisperModel    
│                     │ id: 1                              │
├─────────────────────┼────────────────────────────────────┤
│ audio devices       │                                    │
│                     │ MacBook Pro Microphone (input)     │
│                     │ Display 1 (output)                 │
├─────────────────────┼────────────────────────────────────┤
│ pipes               │                                    │
│                     │ no pipes available                 │
└─────────────────────┴────────────────────────────────────┘
you are using local processing. all your data stays on your computer.

warning: telemetry is enabled. only error-level data will be sent to highlight.io.
to disable, use the --disable-telemetry flag.
2024-10-17T22:14:42.263933Z DEBUG screenpipe: starting pipes
2024-10-17T22:14:42.264052Z  INFO screenpipe_server::server: Server starting on 127.0.0.1:3030    
2024-10-17T22:14:42.269180Z  INFO screenpipe_audio::whisper: device = Metal(MetalDevice(DeviceId(1)))    
2024-10-17T22:14:42.269194Z DEBUG screenpipe_audio::whisper: Fetching model files    
2024-10-17T22:14:42.269319Z DEBUG screenpipe_audio::whisper: Parsing config and tokenizer    
2024-10-17T22:14:42.315783Z DEBUG screenpipe_audio::whisper: Loading model weights    
2024-10-17T22:14:42.579240Z DEBUG screenpipe_audio::whisper: WhisperModel initialization complete    
2024-10-17T22:14:42.582383Z  INFO screenpipe_audio::vad_engine: Initializing SileroVad...
2024-10-17T22:14:42.582430Z  INFO screenpipe_audio::vad_engine: SileroVad Model downloaded to: "/Users/louisbeaumont/Library/Caches/screenpipe/vad/silero_vad.onnx"
2024-10-17T22:14:42.606608Z DEBUG screenpipe_audio::vad_engine: SileroVad initialized successfully    
2024-10-17T22:14:42.606627Z DEBUG screenpipe_server::core: Starting video recording for monitor [1]    
2024-10-17T22:14:42.606631Z DEBUG screenpipe_server::core: Starting video recording for monitor 1    
2024-10-17T22:14:42.606649Z DEBUG screenpipe_audio::stt: Waiting for input from input_receiver    
2024-10-17T22:14:42.606663Z DEBUG screenpipe_server::core: record_video: Starting    
2024-10-17T22:14:42.606673Z  INFO screenpipe_server::video: Starting new video capture    
2024-10-17T22:14:42.606679Z  INFO screenpipe_server::video: Started capture thread    
2024-10-17T22:14:42.606702Z DEBUG screenpipe_server::video: Starting save_frames_as_video function    
2024-10-17T22:14:42.606707Z DEBUG screenpipe_server::video: Starting new FFmpeg process    
2024-10-17T22:14:42.606714Z DEBUG screenpipe_vision::core: continuous_capture: Starting using monitor: 1    
2024-10-17T22:14:42.699725Z DEBUG screenpipe_vision::core: Captured screenshot on monitor 1 with hash: 2376803000610031798    
2024-10-17T22:14:42.699742Z DEBUG screenpipe_vision::utils: No previous image to compare for frame 0    
2024-10-17T22:14:42.701680Z DEBUG screenpipe_vision::core: Performing OCR for frame number since beginning of program 0    
2024-10-17T22:14:43.592347Z DEBUG screenpipe_vision::core: OCR task processed frame 0 with 1 windows in 890.656083ms, average confidence: 0.65    
2024-10-17T22:14:43.592837Z DEBUG screenpipe_server::video: Received frame 0 for queueing    
2024-10-17T22:14:43.592844Z DEBUG screenpipe_server::video: Frame 0 pushed to queues. Queue lengths: 1, 1    
2024-10-17T22:14:43.594448Z DEBUG screenpipe_server::video: Got first frame for new chunk    
2024-10-17T22:14:43.613334Z  INFO screenpipe_server::video: Starting FFmpeg process for file: /Users/louisbeaumont/.screenpipe/data/monitor_1_2024-10-17_22-14-43.mp4    
2024-10-17T22:14:43.613374Z DEBUG screenpipe_core::ffmpeg: Starting search for ffmpeg executable    
2024-10-17T22:14:43.613555Z DEBUG screenpipe_core::ffmpeg: ffmpeg not found in PATH    
2024-10-17T22:14:43.613575Z DEBUG screenpipe_core::ffmpeg: Current working directory: "/Users/louisbeaumont/Documents/screen-pipe"    
2024-10-17T22:14:43.613581Z DEBUG screenpipe_core::ffmpeg: ffmpeg not found in current working directory    
2024-10-17T22:14:43.613586Z DEBUG screenpipe_core::ffmpeg: Executable folder: "/Users/louisbeaumont/Documents/screen-pipe/target/release"    
2024-10-17T22:14:43.613600Z DEBUG screenpipe_core::ffmpeg: Found ffmpeg in executable folder: "/Users/louisbeaumont/Documents/screen-pipe/target/release/ffmpeg"    
2024-10-17T22:14:43.613610Z DEBUG screenpipe_server::video: FFmpeg command: Command { std: "/Users/louisbeaumont/Documents/screen-pipe/target/release/ffmpeg" "-f" "image2pipe" "-vcodec" "png" "-r" "0.2" "-i" "-" "-vf" "pad=width=ceil(iw/2)*2:height=ceil(ih/2)*2" "-vcodec" "libx264" "-preset" "ultrafast" "-crf" "23" "-pix_fmt" "yuv420p" "/Users/louisbeaumont/.screenpipe/data/monitor_1_2024-10-17_22-14-43.mp4", kill_on_drop: false }    
2024-10-17T22:14:43.613903Z DEBUG screenpipe_server::video: FFmpeg process spawned    
2024-10-17T22:14:43.614295Z DEBUG screenpipe_server::core: record_video: Inserted new video chunk: /Users/louisbeaumont/.screenpipe/data/monitor_1_2024-10-17_22-14-43.mp4    
thread 'tokio-runtime-worker' panicked at /Users/louisbeaumont/Documents/screen-pipe/screenpipe-server/src/video.rs:215:26:
Failed to write first frame to ffmpeg: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by louis030195** [comment]
alright this wasted enough of my time

**Pull request closed without merging**
