### PR TITLE
Integration test

### PR DESCRIPTION
**Pull request by daveads**
/claim #225 

- [x] Ensure the code builds and runs the CLI on both Windows and Linux.
- [x] Simulate audio and screen devices in GitHub Actions.
- [x] Run the simulation for 60 seconds to check for crashes.

Currently, displaying images to test OCR and adding voice to the audio for transcription only works correctly on Linux.

### CODE REVIEW

**Comment by daveads** [comment]
@louis030195  Windows isn't properly tested... i should push some commit later tomorrow...

**Comment by daveads** [comment]
windows currently works fine... 


https://github.com/daveads/screenpipe/actions/runs/11252745271/job/31286535560



- [x] Ensure the code builds and runs the CLI on both Windows and Linux.
- [x] Simulate audio and screen devices in GitHub Actions.
- [x] Run the simulation for 60 seconds to check for crashes.

**Comment by daveads** [comment]
Linux 

https://github.com/daveads/screenpipe/actions/runs/11253325796/job/31288345708

**Comment by daveads** [comment]
can you review now ?

**Comment by louis030195** [comment]
@daveads hey i checked all, amazing work!

/approve

**Pull request merged**
