### PR TITLE
fix: Add native-tls to hf-hub

### LINKED ISSUE #730: [bug] $150 screenpipe self signed certs issue - tls connection init failed
**describe the bug**
brief description of the bug.

**to reproduce**
1. Install screenpipe via homebrew
2. Start screenpipe via command line

**expected behavior**
Seeing the following error:
```
2024-11-21T19:08:28.461123Z ERROR screenpipe: continuous recording error: request error: https://huggingface.co/openai/whisper-large-v3-turbo/resolve/main/config.json: Connection Failed: tls connection init failed: invalid peer certificate: UnknownIssuer
````

**system info**
- os: 15.1 (24B83)
- screenpipe version: 0.1.98

**additional context**
It's related to a self signed certificate. The certificate is trusted in the MacOs KeyChain. However, it is not recognized by screenpipe. Is there a way to let screenpipe trust this self signed cert?

### PR DESCRIPTION
**Pull request by neo773**
image

/claim #730
/closes #730

### CODE REVIEW

**Comment by louis030195** [comment]
@neo773 does this still support the hack for chinese mirror?

**Comment by neo773** [comment]
> @neo773 does this still support the hack for chinese mirror?

yes, china mirror support is merged upstream

**Comment by joshuaauger** [comment]
@neo773 can you provide me with some steps to build locally, still not working for me.

**Comment by louis030195** [comment]
how can i test?

**Comment by louis030195** [comment]
/approve

trusting you it works

**Comment by neo773** [comment]
@joshuaauger 
Hi, can you paste the build logs?

**Comment by joshuaauger** [comment]
Logs from build and logs from process attached.

[screenpipe-logs.txt](https://github.com/user-attachments/files/18154348/screenpipe-logs.txt)
[screenpipe-bin-logs.txt](https://github.com/user-attachments/files/18154364/screenpipe-bin-logs.txt)

**Comment by joshuaauger** [comment]
https://github.com/mediar-ai/screenpipe/pull/986

@neo773 Can you check this out, these changes worked for me.

**Pull request merged**
