### PR TITLE
feat: add pipe for loom

### PR DESCRIPTION
**Pull request by tribhuwan-kumar**
---
name: pull request
about: [description](https://github.com/mediar-ai/screenpipe/issues/583#issuecomment-2450318041) [demo](https://github.com/mediar-ai/screenpipe/issues/583#issuecomment-2450791083)
ps: there is some video rendering issue in edge, fixing it

feat: #583 
/claim #583

---

## description
brief description of the changes in this pr.

related issue: #583 

## type of change
- [ ] bug fix
- [x] new feature
- [ ] breaking change
- [ ] documentation update

## how to test

add a few steps to test the pr in the most time efficient way.

1. 
2. 
3. 

if relevant add screenshots or screen captures to prove that this PR works to save us time.

## checklist
- [ ] MOST IMPORTANT: this PR will require less than 30 min to review, merge, and release to production and not crash in the hand of thousands of users
- [ ] i have read the [CONTRIBUTING.md](https://github.com/mediar-ai/screenpipe/blob/main/CONTRIBUTING.md) file 
- [ ] i have updated the documentation if necessary
- [ ] my changes generate no new warnings
- [ ] i have added tests that prove my fix is effective or that my feature works

## additional notes
any other relevant information about the pr.

### CODE REVIEW

**Comment by louis030195** [comment]
@tribhuwan-kumar whats the status of this PR again?

looks decent to merge already, can do audio later

**Comment by tribhuwan-kumar** [comment]
> @tribhuwan-kumar whats the status of this PR again?

same as [prior](https://github.com/mediar-ai/screenpipe/issues/583#issuecomment-2450318041), just need to embed audio in video. i'll do it in free time cz there is some ffmpeg stuff to do!

> looks decent to merge already, can do audio later

if you're okay with it then you can merge it!

> also, would you want to sell this pipe? dm on discord @louis030195
> we can make it easy to charge for it through the pipe store and you get the revenue

i don't get it. "sell this pipe" isn't that bounty is for creating this pipe?

**Comment by louis030195** [comment]
@tribhuwan-kumar we're setting up things so you can charge for pipes in the pipe store for for example people would have to pay $50 one time payment to use your pipe

**Pull request merged**
