### PR TITLE
Add Windows ARM64 CI support

### LINKED ISSUE #430: implement support for windows ARM in `release-app.yml`
implement support for windows ARM in `release-app.yml`

definition of done:
- PR that implement windows arm build in `release-app.yml`
- tested on windows arm device (eg you ran the whole ci yourself, installed the result on a machine and it works)

if there are any issues with the CLI in itself we can revision this issue 

please test, do not ask me to spend 2h on fixing your contribution

/bounty 200

### PR DESCRIPTION
**Pull request by Neptune650**
/claim #430
/closes #430
## description
 
Add support for Windows ARM64 CI in release-app.yml, has been tested in Travis CI and Windows Surface.
 
related issue: #430

Reopened due to repository creation

### CODE REVIEW

**Comment by Neptune650** [comment]
@louis030195 Also, GitHub Actions offers larger runners with Windows ARM64 native support (https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners/about-larger-runners)

You might be interested, since cross compilation tends to be slower.

**Comment by louis030195** [comment]
Screenshot 2024-10-09 at 16 10 23


@Neptune650 just created this one, let me know if you can use it or anything i need to do, also if you have any idea of how much it will cost (so unclear their billing)

**Comment by louis030195** [comment]
@Neptune650 just fyi

i see some v8 code stuff, i actually removed deno lib dependency, the only dependency is deno CLI now (which facing some issue to release on windows actually) but it should be easier to implement windows arm now 

sorry for the changes, can you update this PR? seems like the official deno build does not offer windows arm though https://docs.deno.com/runtime/getting_started/installation/

maybe through cargo install?

`cargo install deno --locked`

giving you part of the bounty for the effort for now, can you try to install deno cli in windows arm in the pre_build.js? (this file is kinda dirty but do its job)

/tip $80 @Neptune650

**Comment by Neptune650** [comment]
> @Neptune650 just fyi
> 
> i see some v8 code stuff, i actually removed deno lib dependency, the only dependency is deno CLI now (which facing some issue to release on windows actually) but it should be easier to implement windows arm now
> 
> sorry for the changes, can you update this PR? seems like the official deno build does not offer windows arm though https://docs.deno.com/runtime/getting_started/installation/
> 
> maybe through cargo install?
> 
> `cargo install deno --locked`
> 
> giving you part of the bounty for the effort for now, can you try to install deno cli in windows arm in the pre_build.js? (this file is kinda dirty but do its job)
> 
> /tip $80 @Neptune650

Thanks for the tip, but I'm not sure what happens because I haven't received it... no idea why.

I'll see how we can build Deno for Windows ARM64

**Comment by louis030195** [comment]
@Neptune650 will fix algora

i am stuck atm in installing deno cli in windows, trying to fix now

**Comment by Neptune650** [comment]
> @Neptune650 will fix algora
> 
> i am stuck atm in installing deno cli in windows, trying to fix now

Alright, do tell me if you need assistance regarding fixing the Deno CLI

**Comment by Neptune650** [comment]
@louis030195 Hello, I'd like to point out two things, first is that since GitHub Runners don't have GPUs by default, the Rust CI takes a lot of time, this leads to it being cancelled, there are three possible solutions:
- Use GPU larger runners, I can set up these for you if needed with Actions: https://github.blog/changelog/2024-07-08-github-actions-gpu-hosted-runners-are-now-generally-available/
- Use larger runners with more time available to run.
- Remove these tests altogether.

Thoughts?

**Comment by Neptune650** [comment]
> Screenshot 2024-10-09 at 16 10 23
> 
> @Neptune650 just created this one, let me know if you can use it or anything i need to do, also if you have any idea of how much it will cost (so unclear their billing)

And regarding this, the pricing for the configuration you picked will be $0.08 per minute ran.

**Comment by Neptune650** [comment]
@louis030195 Also I'm not quite sure yet how I could get access to these runners to start testing the Actions under Windows ARM directly, any suggestion?

**Comment by louis030195** [comment]
> @louis030195 Also I'm not quite sure yet how I could get access to these runners to start testing the Actions under Windows ARM directly, any suggestion?

not sure what i need to do to let you access the runners 

i'd prefer do whatever to use bigger runner, if we can reduce build time also it will be extremely valuable

**Comment by Neptune650** [comment]
> > @louis030195 Also I'm not quite sure yet how I could get access to these runners to start testing the Actions under Windows ARM directly, any suggestion?
> 
> not sure what i need to do to let you access the runners
> 
> i'd prefer do whatever to use bigger runner, if we can reduce build time also it will be extremely valuable

I think the only way is giving access to the organization but I don't think that's very convenient, perhaps accepting my Actions changes each time? Not sure.

**Comment by louis030195** [comment]
there is a chance that we switch to `bun` instead of `deno` in the upcoming week(s) to run pipes since `deno` in the end provides little upsides and too many downsides (does not support well nextjs, not even easy to write Rust extensions)

likely if going to `bun` we'll write Rust webassembly extensions for screenpipe-js SDK or another hack

bun does not seem to support windows ARM well too https://github.com/oven-sh/bun/issues/9824

**Comment by Neptune650** [comment]
> there is a chance that we switch to `bun` instead of `deno` in the upcoming week(s) to run pipes since `deno` in the end provides little upsides and too many downsides (does not support well nextjs, not even easy to write Rust extensions)
> 
> likely if going to `bun` we'll write Rust webassembly extensions for screenpipe-js SDK or another hack
> 
> bun does not seem to support windows ARM well too [oven-sh/bun#9824](https://github.com/oven-sh/bun/issues/9824)

@louis030195 From what I read, even when building from source, it doesn't seem like Bun supports Windows ARM64 natively, so what should be done? This is a pretty big blocker.

**Comment by louis030195** [comment]
@Neptune650 let's pause this issue for now, unless more people ask for windows ARM

**Comment by Neptune650** [comment]
> @Neptune650 let's pause this issue for now, unless more people ask for windows ARM

@louis030195 That's okay with me

**Comment by donjjones** [comment]
> @Neptune650 let's pause this issue for now, unless more people ask for windows ARM

I'm interested in support for Windows on ARM, willing to test

**Comment by louis030195** [comment]
one way to do this is to disable the "pipe store" feature when it's ARM windows (which is the one that uses `bun` which seems hard to compile for windows arm)

**Comment by Neptune650** [comment]
> one way to do this is to disable the "pipe store" feature when it's ARM windows (which is the one that uses `bun` which seems hard to compile for windows arm)

@louis030195 Well another issue is ONNX, which is only supported in ARM windows if using CPU - which is extremely slow.

**Comment by louis030195** [comment]
> > one way to do this is to disable the "pipe store" feature when it's ARM windows (which is the one that uses `bun` which seems hard to compile for windows arm)
> 
> @louis030195 Well another issue is ONNX, which is only supported in ARM windows if using CPU - which is extremely slow.

i think most people have no GPU anyway and it seem to work fine still

**Pull request closed without merging**
