### PR TITLE
fix windows self hosted build 

### LINKED ISSUE #1018: [bounty] fix windows self hosted build
https://github.com/mediar-ai/screenpipe/actions/runs/12417863942/job/34669798423

/bounty 100

### PR DESCRIPTION
**Pull request by asr2003**
---
name: pull request
about: submit changes to the project
title: "[pr] "
labels: ''
assignees: ''

---

## description
fix build

related issue: #
Fixes #1018

### CODE REVIEW

**Comment by asr2003** [comment]
@louis030195 The failure in runner from the logs appears due to NSIS (`makensis.exe`) not being found during the bundling process. 

I have added it explicitly but to test in local repo the windows build doesn't trigger. Can you trigger `release-app` workflow?

**Comment by louis030195** [comment]
i cant trigger on a pr/branch

will test on main and approve if it works

**Comment by louis030195** [comment]
nope https://github.com/mediar-ai/screenpipe/actions/runs/12436812484/job/34725421033

**Comment by asr2003** [comment]
@louis030195 Sorry the download link has been misplaced and I have tested in local with same script added for NSIS installation and here is o/p:

```
PS C:\Users\asr\Desktop> .\script.ps1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   627  100   627    0     0    966      0 --:--:-- --:--:-- --:--:--   970
100   369  100   369    0     0    208      0  0:00:01  0:00:01 --:--:--   821
100 1525k  100 1525k    0     0   318k      0  0:00:04  0:00:04 --:--:--  636k
v3.10
```

**Comment by louis030195** [comment]
nope :(

https://github.com/mediar-ai/screenpipe/actions/runs/12445275287/job/34746441938

**Comment by Neptune650** [comment]
> nope :(
> 
> https://github.com/mediar-ai/screenpipe/actions/runs/12445275287/job/34746441938

@louis030195 It doesn't work because I already explained the issue in #1018

Please check Telegram when you can

**Pull request closed without merging**
