### PR TITLE
(feat) macOS/Linux one-liner installation script 

### PR DESCRIPTION
**Pull request by neo773**
Adds install.sh script to handle dynamic library linking and security attributes on macOS (using rpaths and quarantine removal)

https://github.com/user-attachments/assets/841ba5f3-28db-4f5b-b90f-995932ed54c4

## how to test

```bash
sudo ./install.sh
```

/closes https://github.com/mediar-ai/screenpipe/issues/915
/claim https://github.com/mediar-ai/screenpipe/issues/915

### CODE REVIEW

**Comment by louis030195** [comment]
Screenshot 2024-12-11 at 1 03 31 PM

does not work - should not require sudo

**Comment by louis030195** [comment]
Screenshot 2024-12-11 at 1 42 47 PM

**Comment by neo773** [comment]
hmm seems odd to not have xcode tools installed
anyways pushed a commit to install it if it's not present.

**Comment by louis030195** [comment]
Screenshot 2024-12-11 at 2 10 31 PM

**Comment by neo773** [comment]
Can you try
```source ~/.zshrc```

**Comment by louis030195** [comment]
/approve 

good stuff!

**Pull request merged**
