### PR TITLE
feat: add onboarding

### PR DESCRIPTION
**Pull request by tribhuwan-kumar**
[demo](https://drive.google.com/file/d/17WqbTpvUAvmCMVjUn5RU18q1TVKImBZ1/view?usp=sharing)
[demo exe](https://drive.google.com/file/d/1V9QxdIATQjHU1KNQxQF7pRbTyLUGjX_4/view?usp=sharing)
/claim #412

### CODE REVIEW

**Comment by tribhuwan-kumar** [comment]
@louis030195 
please, review and let me know if you want any changes ;)
& I'm thinking to add a quick dev setup on onboadring, that will explain user how to do setup of `ollama` or any other LLMs.

**Comment by louis030195** [comment]
@tribhuwan-kumar this is cool, right now what i think of:

1. sometimes users had issues, app blocking for like 10 min when launching for the first time due to bad internet and there was no user feedback (it was downloading model) and think of doing a `screenpipe setup` command, although not sure it should be done in this PR, related to https://github.com/mediar-ai/screenpipe/pull/383#issuecomment-2397520199
2. onboarding should mention the concept of "pipe" as plugin that leverage your data to get the most out of screenpipe .. (feel free to phrase it correctly), maybe link to docs for devs to build pipes ..
3. in the AI settings it would be cool to add a button "test" to check their settings are correct, most common issues: bad api key, bad URL (e.g. people forget a segment in the ollama url, bad model, like they use llama3.2:latest instead of llama3.2, etc.) it would just make a fetch to the api 

regarding 1 i think this is the part where most people face issues such as:
- most common on macos: too old version of macos (say 13.0 while 15.0 is available)
- windows: sometimes need admin, some audio devices does not work (dunno why #374)
- linux: wayland not supported but will be in a few days #63 (prob tomorrow), weird linux config might have issues

i think it would be amazing in the onboarding to have a part where user decide if he wants to use screenpipe in dev mode using CLI and the UI on top or non dev mode and just click start and show logs and confirm app works, ideally user should see models are being downloaded or if any error clearly to share 

if it helps, code to copy paste CLI: https://github.com/mediar-ai/screenpipe/blob/e4d26ed9ea59328f092705f5b7ddb5b2ce49a936/screenpipe-app-tauri/components/recording-settings.tsx#L359

again the starting recording process well is trickiest part, hope i gave some more context, if you can try some changes toward this is would be great 🙏

**Comment by louis030195** [comment]
also use lower case everywhere to be aligned with the design we use

**Comment by tribhuwan-kumar** [comment]
> 1. sometimes users had issues, app blocking for like 10 min when launching for the first time due to bad internet and there was no user feedback (it was downloading model) and think of doing a `screenpipe setup` command, although not sure it should be done in this PR, related to [Fix/add ffmpeg sidecar #383 (comment)](https://github.com/mediar-ai/screenpipe/pull/383#issuecomment-2397520199) (also i added a settings for users in china which is required in order to download models otherwise need VPN)

If those PRs integrate the `screenpipe setup` command, then I will add a `screenpipe setup` slide in onboarding, and it'll show the status if screenpipe is downloading models or show the errors which is causing that blockage if everything will okay, then it'll let user move on the next slide, if it isn't then it'll tell user to report issue or give a feedback

> 2. onboarding should mention the concept of "pipe" as plugin that leverage your data to get the most out of screenpipe .. (feel free to phrase it correctly), maybe link to docs for devs to build pipes ..

sure, I'll make a dedicated slide for this :) 

> 3. in the AI settings it would be cool to add a button "test" to check their settings are correct, most common issues: bad api key, bad URL (e.g. people forget a segment in the ollama url, bad model, like they use llama3.2:latest instead of llama3.2, etc.) it would just make a fetch to the api

that's a great suggestion, I'll modify the onboarding api setup slide to integrate `test` button for checking the user's api setup is correct or not & will show the error accordingly!
 
> regarding 1 i think this is the part where most people face issues such as:
> 
> * most common on macos: too old version of macos (say 13.0 while 15.0 is available)
> 
> * windows: sometimes need admin, some audio devices does not work (dunno why [i need help making audio transcription work well on windows (bounty size TBD yet) #374](https://github.com/mediar-ai/screenpipe/issues/374))
> 
> * linux: wayland not supported but will be in a few days [$300 - Linux Wayland support  #63](https://github.com/mediar-ai/screenpipe/issues/63) (prob tomorrow), weird linux config might have issues
> 
> 
> i think it would be amazing in the onboarding to have a part where user decide if he wants to use screenpipe in dev mode using CLI and the UI on top or non dev mode and just click start and show logs and confirm app works, ideally user should see models are being downloaded or if any error clearly to share

sure, this will also a neccessary slide, I'll add this slide & this will explain the difference between non-dev and dev mode, after user chooses what he wants to use then the next slide will its respective, if user wants to use non-dev mode then the app will in non-dev mode, if user selects the dev mode then the next slide will be CLI config slide where the configuration guide will be according to user's OS. 

 > also use lower case everywhere to be aligned with the design we use
 
 ops my bad, I’ll make sure to follow the style guide!

**Comment by louis030195** [comment]
also if you can explain how the search works, like two step process when using AI? does not seem clear for some users:

image

**Comment by tribhuwan-kumar** [comment]
for explaining about search work, I'm thinking to add these kinda [pop ups,](https://blog-static.userpilot.com/blog/wp-content/uploads/2018/12/interactive-walkthrough-free-trial-conversion-rate.gif)
or should I explain it in onboarding dialog ?

**Comment by louis030195** [comment]
> for explaining about search work, I'm thinking to add these kinda [pop ups,](https://blog-static.userpilot.com/blog/wp-content/uploads/2018/12/interactive-walkthrough-free-trial-conversion-rate.gif) or should I explain it in onboarding dialog ? 

i'd suggest just dialog

**Comment by louis030195** [comment]
@tribhuwan-kumar can you share video? i don't really use windows 

it's ok if screenpipe setup is not done, my idea is to merge at some point, do a few adjustment and release (including adding screenpipe setup if nobody does it)

**Comment by tribhuwan-kumar** [comment]
> @tribhuwan-kumar can you share video? i don't really use windows

@louis030195 sure, here is a demo video. 

https://github.com/user-attachments/assets/e694f96e-a086-41ac-9c25-3e871a81de0d


> it's ok if screenpipe setup is not done, my idea is to merge at some point, do a few adjustment and release (including adding screenpipe setup if nobody does it)

then i guess, i should leave the screenpipe status as it is.

**Comment by louis030195** [comment]
@tribhuwan-kumar great work!

i will merge & reward in upcoming days, just finishing up some tasks so i can merge, implement setup and release

**Comment by tribhuwan-kumar** [comment]
> @tribhuwan-kumar great work!
> 
> i will merge & reward in upcoming days, just finishing up some tasks so i can merge, implement setup and release

@louis030195 thank you, one more thing, I added an [`.editorconfig`](https://editorconfig.org/) file for coding style consistency. please make sure to edit it as your desired coding styles!

**Pull request merged**
