### PR TITLE
Implement windows arm64 CI support

### PR DESCRIPTION
**Pull request by Neptune650**
/claim https://github.com/mediar-ai/screenpipe/issues/430
/closes https://github.com/mediar-ai/screenpipe/issues/430

## description
Add support for Windows ARM64 CI in release-app.yml, has been tested in Travis CI and Windows Surface.

related issue: #430 

## type of change
- [ ] bug fix (non-breaking change which fixes an issue)
- [x] new feature (non-breaking change which adds functionality)
- [ ] breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] this change requires a documentation update

### CODE REVIEW

**Comment by louis030195** [comment]
> /claim #430 /closes #430
> 
> ## description
> Add support for Windows ARM64 CI in release-app.yml, has been tested in Travis CI and Windows Surface.
> 
> related issue: #430
> 
> ## type of change
> * [ ]  bug fix (non-breaking change which fixes an issue)
> * [x]  new feature (non-breaking change which adds functionality)
> * [ ]  breaking change (fix or feature that would cause existing functionality to not work as expected)
> * [ ]  this change requires a documentation update

how do i know this works?

**Comment by Neptune650** [comment]
You can approve the CI run or launch a Travis CI instance.

**Comment by Neptune650** [comment]
Also Cargo shows that the Rust code doesn't cause troubles with arm64 builds

**Comment by louis030195** [comment]
@Neptune650 how do i know that after merging, releasing the app, and giving app to windows arm user everything works and it does not crash?

**Comment by louis030195** [comment]
@Neptune650 can you share screen recording on windows surface?

**Comment by Neptune650** [comment]
> @Neptune650 can you share screen recording on windows surface?

I'm free to do that tomorrow

**Comment by louis030195** [comment]
> > @Neptune650 can you share screen recording on windows surface?
> 
> I'm free to do that tomorrow

i mean like just send video recording that shows its arm and screenpipe works, then will merge if it's good!

**Pull request closed without merging**
