### PR TITLE
feat: support h.265 videos on mac

### PR DESCRIPTION
**Pull request by ologbonowiwi**
known limitations: it does not render videos that are partially created. sometimes I saw the video player doesn't playing (as before, like a gray thing as if there's no video), and sometimes a red error of no video found.

please test this locally before merging it @louis030195.

PS: I'll need to run this version of screenpipe which encodes to h265, and let it run for at least 1 minute or so to create a full video which will you be able to play.

~PS2: Just saw the new additions on other PR to improve video experience. merging it to my stuff~

Re-tested it with the recent changes, it appears to be still working.

Browsers tested:
- Safari: OK
- Chrome: OK
- Webview (open as app): OK
- Firefox: OK

/claim #666

### CODE REVIEW

**Comment by louis030195** [comment]
@ologbonowiwi what about search ui?

can you change the video.tsx there too, does it work?

cmd+p -> video.tsx and you see all

**Comment by ologbonowiwi** [comment]
changed the others @louis030195 

I've ran `bunx tauri build` and it worked on the built app. can you check if it works for you?

**Comment by ologbonowiwi** [comment]
Uploading Screen Recording 2024-12-19 at 17.56.52.mov…

**Comment by ologbonowiwi** [comment]
https://github.com/user-attachments/assets/0cc57362-3089-4e34-80fc-94da9080a390

**Comment by louis030195** [comment]
#1010 aint it fix the blank video being written use case? or just did not rebase on main?

**Comment by louis030195** [comment]
i confirm h265 works ♥️

/approve

**Pull request merged**
