### PR TITLE
Full length audio files

### PR DESCRIPTION
**Pull request by EzraEllette**
## description
Adds start_time and end_time to audio_transcriptions table. Saves entire audio recording. In the UI, audio is displayed with the segment start and end time used to control playback to just that particular transcript.

Created a new component for displaying audio. This isn't the most ideal, but it allows us to place markers where the transcript is in the audio file.

image

related issue: #952

## how to test

add a few steps to test the pr in the most time efficient way.

1. run screenpipe
2. ensure that old transcriptions use the entire audio file
3. ensure that new transcriptions start and stop with the transcription.

if relevant add screenshots or screen captures to prove that this PR works to save us time.

/claim #952

### CODE REVIEW

**Comment by louis030195** [comment]
mostly working, just an issue with the audio component in app 

also if by any chance you can mirror the change in pipes/search which is the incoming new path of the search UI

**Comment by louis030195** [comment]
any update

**Comment by NicodemPL** [comment]
also looking forward :)

**Comment by NicodemPL** [comment]
thank you. will test immediately once its pushed to production

**Comment by EzraEllette** [comment]
> thank you. will test immediately once its pushed to production

Your old audio should function normally, but new audio will use markers within the context of a complete audio clip

**Pull request closed without merging**
