### PR TITLE
add simplified Chinese README

### LINKED ISSUE #474: [docs] provide simplified chinese translations
**describe the issue or improvement**

there is growing users coming from China and we'd like translation of README.md and docs 

**suggested changes**

- [ ] translate README.md 
- [ ] translate `content/docs/pages` folder - can you make it a toggle or something to switch between languages?

/bounty 50

### PR DESCRIPTION
**Pull request by varshith257**
---
name: pull request
about: submit changes to the project
title: "[pr] "
labels: ''
assignees: ''

---

Closes #474 
/claim #474 

## type of change
- [ ] bug fix
- [ ] new feature
- [ ] breaking change
- [ ] documentation update

## how to test
1. 
2. 
3. 

## checklist
- [ ] i have read the [CONTRIBUTING.md](../CONTRIBUTING.md) file 
- [ ] i have added the custom cursor AI prompt to my settings as mentioned in CONTRIBUTING.md and used to write this PR
- [ ] my code follows the project's style guidelines
- [ ] i have performed a self-review of my code
- [ ] i have updated the documentation if necessary
- [ ] my changes generate no new warnings
- [ ] i have added tests that prove my fix is effective or that my feature works
- [ ] all tests pass locally with my changes

## additional notes
any other relevant information about the pr.

### CODE REVIEW

**Comment by louis030195** [comment]
@varshith257 can you do it for docs too?

**Comment by varshith257** [comment]
Yes, doing it! Just creating a toggle for it and testing

**Comment by varshith257** [comment]
@jkcs Have a look at the pages and README translated. Meanwhile I will add support for toggle button

**Comment by louis030195** [comment]
@varshith257 hey sorry for the change but decided to only support translation for the readme, will be too much effort to maintain the docs on our side otherwise, do you mind removing it, just having the readme and i'll approve bounty & merge?

**Comment by varshith257** [comment]
Sure!

**Comment by asr2003** [comment]
@louis030195 Done!

**Comment by varshith257** [comment]
@louis030195 Have a review on it!

**Comment by louis030195** [comment]
thx @varshith257 

/approve

**Pull request merged**
