### PR TITLE
Cross-Platform App Icon Fetching Support for Windows and Linux

### PR DESCRIPTION
**Pull request by naaa760**
---
name: pull request
about: submit changes to the project
title: "[pr] "
fix:  #643
/claim #643

Description

- This PR implements cross-platform support for fetching application icons on Windows and Linux, similar to macOS. It extracts icons from executables on Windows and searches for icons in standard directories on Linux, converting them to Base64-encoded PNGs for consistency across platforms.

Type of Change

- bug fix

How to Test

- Run the get_app_icon command on Windows, Linux, and macOS with valid app names and paths.
    Verify the returned icon is a Base64-encoded PNG.
    Ensure the function gracefully handles invalid paths or missing icons.

Checklist

- This PR can be reviewed, merged, and released in less than 30 minutes without causing major issues for users.
- I have read the CONTRIBUTING.md file.
- No new warnings were generated.
- I have added tests that ensure the functionality works across platforms.

Additional Notes

- This PR ensures cross-platform compatibility and consistency in app icons on Linux, Windows, and macOS.

### CODE REVIEW

**Comment by louis030195** [comment]
@naaa760 can you share a screen recording to prove this works?

**Comment by naaa760** [comment]
Hello @louis030195 

right now, I cannot run on the server because of this issue.
Screenshot from 2024-11-08 10-36-27

**Comment by louis030195** [comment]
just to clarify

the point of bounties is that you are going to do the work so i don't have to do it myself

you wrote this code with chatgpt in less than 5 seconds and then sent a PR without testing it which is highly disrespectful

**Comment by naaa760** [comment]
> just to clarify
> 
> the point of bounties is that you are going to do the work so i don't have to do it myself
> 
> you wrote this code with chatgpt in less than 5 seconds and then sent a PR without testing it which is highly disrespectful

No, at that time it runs , but right now what's the error gets in.
I am really sorry for that.
and I did not use chatgpt.

**Pull request closed without merging**
