### PR TITLE
fix: Remove unsued dependencies

### LINKED ISSUE #1005: [bounty] make app smaller
/bounty 50

atm there are tons of dependencies in the app we dont use

also

https://v2.tauri.app/concept/size/

### PR DESCRIPTION
**Pull request by mehul-m-prajapati**
## description
- Remove unsued dependencies

related issue: 
fixes #1005
/claim #1005

## how to test
1. cargo udeps
2. cargo check

d1

---

3.
```
cargo build --release
```
d2

### CODE REVIEW

**Comment by Neptune650** [comment]
Doesn't work because it gets rid of an used library, and doesn't use the profile settings.

**Comment by Neptune650** [comment]
Also, this completely changes the panic behavior now to abort instead of providing important debug info

**Comment by mehul-m-prajapati** [comment]
@Neptune650 : thanks for your review. That was my first draft.

I have added profile settings now.

**Comment by Neptune650** [comment]
Now this is just a copy of what was done in #1009

**Comment by mehul-m-prajapati** [comment]
@Neptune650 : I took a reference from https://v2.tauri.app/concept/size/.

You have also copied it from same.

**Comment by Neptune650** [comment]
Done after my PR and removed incremental too, which I did, despite it not being necessary to remove.

**Comment by mehul-m-prajapati** [comment]
@Neptune650 : you can take bounty.. Seems like too pushy behaviour from this guy @louis030195

**Comment by Neptune650** [comment]
Please don't call me guy cause I'm not, I've been trying to be civil, that's not the issue here, the issue here is that this code doesn't compile and is the issue I was pointing out originally

**Pull request closed without merging**
