### PR TITLE
fix: self hosted windows nsis build error

### PR DESCRIPTION
**Pull request by Dhanus3133**
https://github.com/Dhanus3133/screenpipe/actions/runs/12452753615/job/34762101342#step:29:1925

Fixes: #1018
/claim #1018

### CODE REVIEW

**Comment by Dhanus3133** [comment]
@louis030195 can you please test it out...

**Comment by louis030195** [comment]
>), ["file_associations", "1", "ext", "7"]) }], hash: {}
    Debug [handlebars::render] Rendering helper: "each", params: [PathAndJson { relative_path: Some("deep_link_protocols"), value: Missing }], hash: {}
    Debug [handlebars::render] Rendering helper: "each", params: [PathAndJson { relative_path: Some("resources_ancestors"), value: Context(Array [], ["resources_ancestors"]) }], hash: {}
    Running [tauri_bundler::bundle::windows::nsis] makensis.exe to produce C:\actions-runner\_work\***\***\***-app-tauri\src-tauri\target\x86_64-pc-windows-msvc\release\bundle\nsis\***_0.20.7_x64-setup.exe
    Running [tauri_bundler::bundle::common] Command `C:\Windows\system32\config\systemprofile\AppData\Local\tauri\NSIS\makensis.exe  -INPUTCHARSET UTF8 -OUTPUTCHARSET UTF8 -V4 C:\actions-runner\_work\***\***\***-app-tauri\src-tauri\target\x86_64-pc-windows-msvc\release\nsis\x64\installer.nsi`
Unable to start child process, error 0x2
failed to bundle project: `The system cannot find the file specified. (os error 2)`
    Error [tauri_cli_node] failed to bundle project: `The system cannot find the file specified. (os error 2)`
Error: Command "bunx ["tauri","-vvv","build","--target","x86_64-pc-windows-msvc"]" failed with exit code 1

https://github.com/mediar-ai/screenpipe/actions/runs/12454379955/job/34766627300

nope

@Dhanus3133 did not work

**Comment by Dhanus3133** [comment]
@louis030195 https://github.com/mediar-ai/screenpipe/actions/runs/12454379955/job/34767752644 Noticed your recent workflow triggered, and it seems to have resolved the issue! Not sure if my changes helped out here though.

**Comment by louis030195** [comment]
@Dhanus3133 no your changed did not help, someone else did it 

would appreciate you contribute to another issue if you can, since you got the bounty for free

**Comment by Dhanus3133** [comment]
> @Dhanus3133 no your changed did not help, someone else did it 
> 
> would appreciate you contribute to another issue if you can, since you got the bounty for free 
> 
> 
> 
> 
> 

Sure!

**Pull request merged**
