### PR TITLE
Llm api

### PR DESCRIPTION
**Pull request by EzraEllette**
/claim #409

### CODE REVIEW

**Comment by EzraEllette** [comment]
It would be good to enable streaming

**Comment by EzraEllette** [comment]
@louis030195 once this PR is ready to merge, could you please squash the commits?

**Comment by louis030195** [comment]
@EzraEllette nice work!

i guess without streaming is good enough for now, will check few things then merge

**Comment by EzraEllette** [comment]
Please allow me to rename a few variables first. I'm writing a quick email then I'll push the commit.

**Comment by louis030195** [comment]
> Please allow me to rename a few variables first. I'm writing a quick email then I'll push the commit.

good

just one thing, can you make it possible to disable running the LLM using arg? like --disable-llm or something, because some people don't have powerful computer

**Comment by EzraEllette** [comment]
Do you plan on this feature being enabled by default?

**Comment by louis030195** [comment]
> Do you plan on this feature being enabled by default?

hm i think now it should not be enabled by default because probably only 30% of people would use it right now until we build feature around

**Comment by EzraEllette** [comment]
Okay, I'm working on this

**Comment by EzraEllette** [comment]
👍🏼

**Comment by EzraEllette** [comment]
@louis030195

**Comment by EzraEllette** [comment]
If you think the arg name is ambiguous I can rename it

**Comment by louis030195** [comment]
@EzraEllette great work!

merging

**Comment by louis030195** [comment]
@EzraEllette 

```
curl -X POST "http://localhost:3030/llm/chat" \
     -H "Content-Type: application/json" \
     -d '{
       "messages": [
         {"role": "user", "content": "what is the capital of france?"}
       ],
       "stream": false,
       "max_completion_tokens": 100,
       "temperature": 0.7
     }' | jq

{
  "error": "cannot find tensor lm_head.weight"
}
```

**Comment by EzraEllette** [comment]
I'm looking into this. I tried switching to stable rust, but that didn't affect anything. It's entirely possible that it's an issue with the candle version. 

Can you try running `rm -rf ~/.cache/huggingface/hub/models--meta-llama--Llama-3.2-1B-Instruct` and restarting screenpipe?

this is the command I use to run: `cargo run --package screenpipe-server --bin screenpipe --features metal --features llm -- --enable-llm`
[Cargo copy.lock.txt](https://github.com/user-attachments/files/17283540/Cargo.copy.lock.txt)

**Comment by EzraEllette** [comment]
@louis030195 Did you solve your issue?

**Comment by louis030195** [comment]
> rm -rf ~/.cache/huggingface/hub/models--meta-llama--Llama-3.2-1B-Instruct

```
cargo run --package screenpipe-server --bin screenpipe --features metal --features llm -- --enable-llm

(env) (base) louisbeaumont@louisbeaumontme-macbook:~/Documents/screen-pipe$ curl -X POST "http://localhost:3030/llm/chat"      -H "Content-Type: application/json"      -d '{
       "messages": [
         {"role": "user", "content": "what is the capital of france?"}
       ],
       "stream": false,
       "max_completion_tokens": 100,
       "temperature": 0.7
     }' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   242  100    45  100   197     50    221 --:--:-- --:--:-- --:--:--   271
{
  "error": "cannot find tensor lm_head.weight"
}
```

**Comment by louis030195** [comment]
updated candle pakcages to `0.7.2` and it works

```
"message": {
        "role": "assistant",
        "content": " Paris\nThe official name of the capital of France is Paris. Only London is larger than Paris in terms of area.\n\nParis is located on the Seine River and was founded by the Romans. It has been an important city throughout history, playing a major role in European politics, culture, art, science, fashion, cuisine, cinema, and many other fields. The French language is spoken by about 125 million people worldwide, making it one of the most widely spoken languages globally.\n\nNote: France"
      },
      "logprobs": null,
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 8,
    "completion_tokens": 100,
    "total_tokens": 100,
    "completion_tokens_details": null,
    "tokens_per_second": 18.94180913601721
  }
}
```

**Comment by louis030195** [comment]
],
  "usage": {
    "prompt_tokens": 8,
    "completion_tokens": 100,
    "total_tokens": 100,
    "completion_tokens_details": null,
    "tokens_per_second": 55.332270283049716
  }
}



in release mode 55 tps :D

**Comment by louis030195** [comment]
@EzraEllette any idea how i could impl JSON mode?


claude suggest some things like this:
```rs
impl Model for Llama {
    fn chat(&self, request: ChatRequest) -> Result<ChatResponse> {
        // ... existing code ...

        let json_mode = request.json_mode;
        let mut output = String::new();
        let mut json_output = String::new();
        let mut in_json = false;

        for index in 0..sample_len {
            // ... existing token generation code ...

            if json_mode {
                if next_token == self.tokenizer.token_to_id("{").unwrap() {
                    in_json = true;
                    json_output.push('{');
                } else if next_token == self.tokenizer.token_to_id("}").unwrap() {
                    in_json = false;
                    json_output.push('}');
                    break;
                } else if in_json {
                    if let Some(t) = tokenizer.next_token(next_token)? {
                        json_output.push_str(&t);
                    }
                }
            } else {
                if let Some(t) = tokenizer.next_token(next_token)? {
                    output.push_str(&t);
                }
            }
        }

        // ... existing code ...

        Ok(ChatResponse {
            // ... other fields ...
            choices: vec![ChatResponseChoice {
                index: 0,
                message: ChatMessage {
                    role: "assistant".to_string(),
                    content: if json_mode { json_output } else { output },
                },
                logprobs: None,
                finish_reason: "stop".to_string(),
            }],
            // ... other fields ...
        })
    }
}

```

like this https://platform.openai.com/docs/guides/structured-outputs/json-mode

but only need basic JSON

**Comment by louis030195** [comment]
https://github.com/EricLBuehler/mistral.rs checking how they do it here

**Comment by louis030195** [comment]
@EzraEllette fyi i think i'll open a new issue to implement using llama-cpp instead https://github.com/utilityai/llama-cpp-rs

just noticing Candle is a good low level lib, like Pytorch, but screenpipe is looking for more ready to use AI tools and currently LLM impl does not support json outputs, and other things

maybe in the future we'd do more low level things but for now i'd rather focus on creating a lib/product/project that brings value and leverage great ecosystem

do you have any thoughts on this?

**Pull request merged**
