### PR TITLE
feat: automate brew formula update

### LINKED ISSUE #692: [bounty] automating official brew update
/bounty 80

basically update https://github.com/mediar-ai/screenpipe/blob/main/.github/workflows/release-cli.yml to properly automate official brew too when ran 

(if linux is too hard just skip for now, focus on macos)

@Anshgrover23 want to give a shot?

### PR DESCRIPTION
**Pull request by krushnarout**
---
name: feat: automate brew formula update
about: automate brew formula update
title: "feat: automate brew formula update"
labels: ''
assignees: ''

---

## description

automate brew formula update using `brew bump-formula-pr`

Closes #692
/claim #692 

## type of change

- [x] new feature

## checklist
- [x] MOST IMPORTANT: this PR will require less than 30 min to review, merge, and release to production and not crash in the hand of thousands of users
- [x] i have read the [CONTRIBUTING.md](https://github.com/mediar-ai/screenpipe/blob/main/CONTRIBUTING.md) file 
- [ ] i have updated the documentation if necessary
- [ ] my changes generate no new warnings
- [ ] i have added tests that prove my fix is effective or that my feature works

## additional notes
any other relevant information about the pr.

### CODE REVIEW

**Comment by louis030195** [comment]
cool, great work!

how can i test this to make sure it works?

**Comment by louis030195** [comment]
https://github.com/Homebrew/homebrew-core/pull/196345/files

@m13v any chance you can add the ui monitoring lib there? (maybe after this PR is merged)

think we need to send PR to brew official to add it

**Comment by krushnarout** [comment]
> cool, great work!
> 
> how can i test this to make sure it works?

Thank you!

Use `--dry-run` to test this locally without creating PR.

```
tmp_dir=$(mktemp -d)
cd "$tmp_dir"

export VERSION="0.1.99"
export GITHUB_REPOSITORY="mediar-ai/screenpipe"
export MATRIX_TARGET="x86_64-apple-darwin"

curl -LO "https://github.com/${GITHUB_REPOSITORY}/releases/download/v${VERSION}/screenpipe-${VERSION}-${MATRIX_TARGET}.tar.gz"

export SHA=$(shasum -a 256 screenpipe-*.tar.gz | cut -d ' ' -f 1)
export URL="https://github.com/${GITHUB_REPOSITORY}/releases/download/v${VERSION}/screenpipe-${VERSION}-${MATRIX_TARGET}.tar.gz"

# Added --dry-run to test without creating PR
brew bump-formula-pr screenpipe \
  --version=${VERSION} \
  --url="${URL}" \
  --sha256="${SHA}" \
  --message="Test: Update screenpipe to version ${VERSION} for ${MATRIX_TARGET}" \
  --no-browse \
  --no-audit \
  --dry-run
  
  cd -
rm -rf "$tmp_dir"
```

https://github.com/user-attachments/assets/ec844163-3307-42e1-8c55-cc111bf4b6ea

**Comment by louis030195** [comment]
/approve
 thanks!

**Comment by louis030195** [comment]
@krushnarout do you have any idea how to make this work for updating the linux brew too?

**Comment by krushnarout** [comment]
> @krushnarout do you have any idea how to make this work for updating the linux brew too?

@louis030195  I’m not sure how to make it work for updating Linux brew at the moment. There's limited information available on this, but if I had more time to look into it, I might be able to find a solution.

**Comment by louis030195** [comment]
@krushnarout fyi this does not work https://github.com/mediar-ai/screenpipe/actions/runs/11958214212

**Comment by louis030195** [comment]
https://github.com/Homebrew/homebrew-core/pull/198524 broken 😕

**Comment by krushnarout** [comment]
> [Homebrew/homebrew-core#198524](https://github.com/Homebrew/homebrew-core/pull/198524) broken 😕

Hi @louis030195! I noticed you haven’t released a new version yet. You can't update the formula without releasing a new version!

**Comment by krushnarout** [comment]
> [Homebrew/homebrew-core#198524](https://github.com/Homebrew/homebrew-core/pull/198524) broken 😕

Hi @louis030195! I noticed you haven't released a new version yet, but you're trying to update the formula without one. Also your repository's formula differs from the Homebrew-core formula. I believe both should be the same.

**Comment by krushnarout** [comment]
> [Homebrew/homebrew-core#198524](https://github.com/Homebrew/homebrew-core/pull/198524) broken 😕

Hi @louis030195! I noticed you haven't released a new version yet, but you're trying to update the formula without one.

**Comment by louis030195** [comment]
@krushnarout what do you mean? 

release-cli usually required: 

```
git tag v<my version>
git push origin v<my version>
```

and it would release to brew end-to-end

now it's just broken

**Comment by krushnarout** [comment]
> @krushnarout what do you mean?
> 
> release-cli usually required:
> 
> ```
> git tag v<my version>
> git push origin v<my version>
> ```
> 
> and it would release to brew end-to-end
> 
> now it's just broken
> 
> i released 3 times, lost 1h of my day and it does not work

I understand your frustration. I tried running a `--dry-run` on my side, and it did show the SHA256 correctly. I mentioned this because I’ve checked how other formulas are updated when they release new versions. There isn’t much information available about this process, and it’s taken me a lot of time as well since Homebrew’s documentation isn’t very clear on this topic.

**Pull request merged**
