### PR TITLE
386 add update to tray

### PR DESCRIPTION
**Pull request by EzraEllette**
/claim #386

Icons need to be updated.

How should we determine which color icon to use? (light vs dark mode for example.)

### CODE REVIEW

**Review by defihook — COMMENTED** [review]
usetoast

**Comment by louis030195** [comment]
@defihook you are blocked

**Comment by louis030195** [comment]
@EzraEllette nice!!

>How should we determine which color icon to use? (light vs dark mode for example.)

hmm is there such a thing as dark/light mode in the tray bar? on macos my tray bar seems always black background?

**Comment by EzraEllette** [comment]
> @EzraEllette nice!!
> 
> > How should we determine which color icon to use? (light vs dark mode for example.)
> 
> hmm is there such a thing as dark/light mode in the tray bar? on macos my tray bar seems always black background?

My Traybar icons are usually white. I'll just use white

**Comment by louis030195** [comment]
@EzraEllette i see you commented the JS code

can you make sure the sidecar stops when updating?

maybe just kill using the kill app command 

esp. for windows sidecar does not close well sometimes, for some reason auto destruct feat does not work on windows https://github.com/mediar-ai/screenpipe/blob/main/screenpipe-server/src/auto_destruct.rs

only use case is if user is using dev mode and running CLI built from source and front end built from CI but i think it's fine

then put to review the PR ill test it 🙏

**Comment by EzraEllette** [comment]
> @EzraEllette i see you commented the JS code
> 
> can you make sure the sidecar stops when updating?
> 
> maybe just kill using the kill app command
> 
> esp. for windows sidecar does not close well sometimes, for some reason auto destruct feat does not work on windows https://github.com/mediar-ai/screenpipe/blob/main/screenpipe-server/src/auto_destruct.rs
> 
> only use case is if user is using dev mode and running CLI built from source and front end built from CI but i think it's fine
> 
> then put to review the PR ill test it 🙏

I'll update that. 

Should there be another PR for updating the default system tray icon to the icon provided in the folder?

**Comment by louis030195** [comment]
@

> > @EzraEllette i see you commented the JS code
> > can you make sure the sidecar stops when updating?
> > maybe just kill using the kill app command
> > esp. for windows sidecar does not close well sometimes, for some reason auto destruct feat does not work on windows https://github.com/mediar-ai/screenpipe/blob/main/screenpipe-server/src/auto_destruct.rs
> > only use case is if user is using dev mode and running CLI built from source and front end built from CI but i think it's fine
> > then put to review the PR ill test it 🙏
> 
> I'll update that.
> 
> Should there be another PR for updating the default system tray icon to the icon provided in the folder?

that would be great! or in this PR would work too

**Comment by EzraEllette** [comment]
> @
> 
> > > @EzraEllette i see you commented the JS code
> > > can you make sure the sidecar stops when updating?
> > > maybe just kill using the kill app command
> > > esp. for windows sidecar does not close well sometimes, for some reason auto destruct feat does not work on windows https://github.com/mediar-ai/screenpipe/blob/main/screenpipe-server/src/auto_destruct.rs
> > > only use case is if user is using dev mode and running CLI built from source and front end built from CI but i think it's fine
> > > then put to review the PR ill test it 🙏
> > 
> > 
> > I'll update that.
> > Should there be another PR for updating the default system tray icon to the icon provided in the folder?
> 
> that would be great! or in this PR would work too

@louis030195 Quick update: sidecar restarts when calling `kill_all_screenpipes`, but I'm not sure you meant that's what I am supposed to invoke to kill the sidecar. 

I didn't find anything else, so I added a command `kill_sidecar` that calls `kill_all_screenpipes` and aborts the task that restarts sidecar on an interval.

I'll update the tray icon in my next commit.

**Comment by louis030195** [comment]
> > @
> > > > @EzraEllette i see you commented the JS code
> > > > can you make sure the sidecar stops when updating?
> > > > maybe just kill using the kill app command
> > > > esp. for windows sidecar does not close well sometimes, for some reason auto destruct feat does not work on windows https://github.com/mediar-ai/screenpipe/blob/main/screenpipe-server/src/auto_destruct.rs
> > > > only use case is if user is using dev mode and running CLI built from source and front end built from CI but i think it's fine
> > > > then put to review the PR ill test it 🙏
> > > 
> > > 
> > > I'll update that.
> > > Should there be another PR for updating the default system tray icon to the icon provided in the folder?
> > 
> > 
> > that would be great! or in this PR would work too
> 
> @louis030195 Quick update: sidecar restarts when calling `kill_all_screenpipes`, but I'm not sure you meant that's what I am supposed to invoke to kill the sidecar.
> 
> I didn't find anything else, so I added a command `kill_sidecar` that calls `kill_all_screenpipes` and aborts the task that restarts sidecar on an interval.
> 
> I'll update the tray icon in my next commit.

yeah basically windows has a weird setup install UX that looks like Windows XP/dinosaur age software that block if the CLI is running in the background because it cannot update files because it's being used so need to properly make sure CLI/app is closed on windows

**Comment by EzraEllette** [comment]
> > > @
> > > > > @EzraEllette i see you commented the JS code
> > > > > can you make sure the sidecar stops when updating?
> > > > > maybe just kill using the kill app command
> > > > > esp. for windows sidecar does not close well sometimes, for some reason auto destruct feat does not work on windows https://github.com/mediar-ai/screenpipe/blob/main/screenpipe-server/src/auto_destruct.rs
> > > > > only use case is if user is using dev mode and running CLI built from source and front end built from CI but i think it's fine
> > > > > then put to review the PR ill test it 🙏
> > > > 
> > > > 
> > > > I'll update that.
> > > > Should there be another PR for updating the default system tray icon to the icon provided in the folder?
> > > 
> > > 
> > > that would be great! or in this PR would work too
> > 
> > 
> > @louis030195 Quick update: sidecar restarts when calling `kill_all_screenpipes`, but I'm not sure you meant that's what I am supposed to invoke to kill the sidecar.
> > I didn't find anything else, so I added a command `kill_sidecar` that calls `kill_all_screenpipes` and aborts the task that restarts sidecar on an interval.
> > I'll update the tray icon in my next commit.
> 
> yeah basically windows has a weird setup install UX that looks like Windows XP/dinosaur age software that block if the CLI is running in the background because it cannot update files because it's being used so need to properly make sure CLI/app is closed on windows

Okay, should be ready. triple check the code around killing sidecar.

As for commenting out the update check in the frontend, I did that because It wasn't allowing me to prevent the update. The cancel button triggers the useEffect hook and leads to an infinite loop of update notifications.

I can uncomment it if you would like.

**Comment by EzraEllette** [comment]
P.S. I got distracted by ben franklin, I really just want to update the database manager so that I can store everything on my server.

**Pull request merged**
