### PR TITLE
fix: mac sonoma 14.7 segfault

### PR DESCRIPTION
**Pull request by ologbonowiwi**
- **fix: comment out input by host segfaulting**
- **fix: use output device instead of input device**

before my changes:
Screenshot 2024-10-12 at 15 41 19
after:
Screenshot 2024-10-12 at 15 41 48

---
name: pull request
about: submit changes to the project
title: "[pr] "
labels: ''
assignees: ''

---

## description
apparently there's unsafe code under the input retrieving on cpal (assuming this because the error it was not possible to catch/handle the error, it just shuts the app down without any logs). I've commented out this code, and also changed a place where the method name is `default_output_device`, but was internally using `default_input_device` instead

related issue: #

## type of change
- [x] bug fix
- [ ] new feature
- [ ] breaking change
- [ ] documentation update

## checklist
- [x] i have read the [CONTRIBUTING.md](https://github.com/mediar-ai/screenpipe/blob/main/CONTRIBUTING.md) file 
- [ ] i have added the custom cursor AI prompt to my settings as mentioned in CONTRIBUTING.md and used to write this PR
- [x] my code follows the project's style guidelines
- [x] i have performed a self-review of my code
- [ ] i have updated the documentation if necessary
- [x] my changes generate no new warnings
- [ ] i have added tests that prove my fix is effective or that my feature works
- [x] all tests pass locally with my changes

## additional notes
not sure if anything broke as side effect. I highly recommend test on another machine to confirm everything works fine before merging it.

image

### CODE REVIEW

**Comment by louis030195** [comment]
@ologbonowiwi can you still get transcription from Display audio?

**Comment by ologbonowiwi** [comment]
not really @louis030195. I couldn't try the app because of this error, so I can't know how it behaved before.

trying to test this rn, but the app is erroring-out and I can't give access on permissions because it's not even appearing there
image

**Comment by ologbonowiwi** [comment]
can you try it out to see if the problem is my change? I can't test the version without my change because the build fails.

**Comment by ologbonowiwi** [comment]
yeah, almost giving up here. found https://github.com/mediar-ai/screenpipe/issues/382 and tried the script mentioned there, but didn't work out for me. I'll see if I can get it running on endeavouros when I get a chance

**Pull request closed without merging**
