### PR TITLE
disable update check in dev mode

### PR DESCRIPTION
**Pull request by EzraEllette**
disable update check in dev mode.

### CODE REVIEW

**Comment by EzraEllette** [comment]
https://github.com/user-attachments/assets/0f66d265-1e6f-4e2e-b96f-dbb537f30024

**Comment by louis030195** [comment]
why?

for me this was an issue when using `bun tauri dev` it would show popup dialog

**Comment by EzraEllette** [comment]
I may have understood this as the dev mode within screenpipe, not during development.

**Comment by EzraEllette** [comment]
https://github.com/mediar-ai/screenpipe/issues/539

**Comment by EzraEllette** [comment]
We can close this.

**Pull request closed without merging**
