### PR TITLE
Use recursive copy for MKL

### PR DESCRIPTION
**Pull request by Neptune650**
@louis030195 One last change since you were a little too quick with the latest PR.

### CODE REVIEW

**Comment by Neptune650** [comment]
@louis030195 If it fails again, just merge this.

**Comment by Neptune650** [comment]
@louis030195 https://github.com/mediar-ai/screenpipe/commit/e3ebed2d2d25f4c7fb96df55370aa6cd384d642f appears to have broken building.

**Comment by louis030195** [comment]
https://github.com/mediar-ai/screenpipe/actions/runs/11581165046/job/32241290226

>ERROR: Could not find dependency: libiomp5.so

@Neptune650 any idea?

**Comment by Neptune650** [comment]
> https://github.com/mediar-ai/screenpipe/actions/runs/11581165046/job/32241290226
> 
> > ERROR: Could not find dependency: libiomp5.so
> 
> @Neptune650 any idea?

@louis030195 Add 
```
  if [[ "ubuntu-22.04" == "ubuntu-22.04" ]]; then
    export PKG_CONFIG_PATH="~/.local/lib/pkgconfig:$PKG_CONFIG_PATH"
    export MKLROOT="/opt/intel/mkl"
  fi
```
To the "build" step (not build cli)

**Comment by louis030195** [comment]
@Neptune650 https://github.com/mediar-ai/screenpipe/actions/runs/11582012318/job/32244048059#step:23:25

**Comment by Neptune650** [comment]
@louis030195 Add:
```
sudo cp -rfv ~/.local/lib/* ~/.local/include/* /usr/lib/x86_64-linux-gnu/
```
To the end of the "Install MKL in Linux" step
It should fix everything.

**Comment by louis030195** [comment]
@Neptune650 trying now

not even sure why tauri app complains, the mkl is only on the CLI

**Comment by Neptune650** [comment]
> @Neptune650 trying now
> 
> not even sure why tauri app complains, the mkl is only on the CLI

@louis030195 I'm pretty sure it would've worked this time - but failed because it doesn't retry downloading files, so randomly it fails. Try retrying the build ig.

**Pull request merged**
